name: context_use
description: ""
version: 0.0.1-dev.1
homepage:

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.17.0-1.0.pre.38 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  context_watch: ^2.0.0-dev.5

flutter:
