name: example
description: "context_plus example"
publish_to: "none"
version: 1.0.0

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  context_plus: ^2.2.0
  rxdart: ^0.27.7
  syntax_highlight: ^0.3.0
  dolumns: ^2.0.1
  url_router: ^0.2.1+3
  linked_scroll_controller: ^0.2.0
  performance: ^0.1.1

  # Signals
  signals_flutter: ^1.0.1
  context_watch_signals: ^1.0.0-dev.2

  # MobX
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  context_watch_mobx: ^1.0.4

  # Beacon
  state_beacon: ^0.14.5
  context_watch_beacon: ^1.0.0-dev.2

  # Bloc
  flutter_bloc: ^8.1.2
  context_watch_bloc: ^1.0.4

  # GetX
  get: ^4.6.6
  context_watch_getx: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/examples/animation_controller/variants/
    - lib/examples/rainbow/variants/
    - lib/examples/derived_state/variants/
    - lib/examples/counter/variants/
    - lib/examples/counter_with_propagation/variants/
    - lib/examples/nested_scopes/variants/
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf
