name: context_plus
sdkPath: .fvm/flutter_sdk

ide:
  intellij:
    moduleNamePrefix: ""

packages:
  - example
  - packages/*

scripts:
  test:
    exec: flutter test
    packageFilters:
      flutter: true
      dirExists: test
      noPrivate: true