name: context_watch_beacon
description: "context_watch adapter for state_beacon package"
version: 1.0.0-dev.1
homepage: https://github.com/s0nerik/context_watch
repository: https://github.com/s0nerik/context_watch

environment:
    sdk: ">=3.0.6 <4.0.0"
    flutter: ">=3.2.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    context_watch_base: ^1.0.0-dev.1
    state_beacon: ^0.13.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
