name: context_plus
description: "Tighter integration between context_use, context_ref and context_watch."
version: 1.0.0-dev.1
homepage:

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.17.0-1.0.pre.38 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  context_ref: ^1.0.0-dev.1
  context_watch: ^2.0.0-dev.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
