name: Deploy examples to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          flutter-version: 3.27.0-0.2.pre
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: example
          customArgs: --wasm
